### ISSUE TITLE
利用Github action进行云部署

### ISSUE THREAD

**Issue by ghost** [91khr/91khr.github.io#2]
如题

[实验地址x半残废状态](https://xuwillie.github.io/theme-console)
[源码](https://github.com/xuwillie/theme-console)_

使用Pandoc, Github Action, Python, Shell Script拼凑的项目

实现了 自动发布，自动获取文章列表。

//////////////////////////////////////
喜欢你的网站风格. 希望对你有帮助！

TmljZSB0byBtZWV0IHlvdQ==

**Comment by senioria** [comment]
唔... 如果这个issue并非出于手误的话... (因为感觉senioria的blog并不值得这样的评价 >_<) 谢谢的说 (超小声(

senioria也在计划重构build system, 不过大概不是很打算用c++之外的东西做框架... 至于gh action...  
其实gh自己有个默认的用于发布gh pages的action的样子... ? (超小声(

总之感谢支持 x_x (超小声(
